-- 20260405_add_course_section_schedule.sql
-- Purpose:
-- 1) Add table course_section_schedule for supporting multiple weekly schedules per course section
-- 2) Add indexes for faster conflict lookup
-- 3) Backfill one schedule row for each existing course_section

BEGIN;

CREATE TABLE IF NOT EXISTS course_section_schedule (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_section_id INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL,
    start_period INTEGER NOT NULL,
    number_of_periods INTEGER NOT NULL,
    start_time TIMESTAMP NULL,
    end_time TIMESTAMP NULL,
    room_id INTEGER NULL,
    is_cancel BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NULL DEFAULT NOW(),
    updated_at TIMESTAMP NULL DEFAULT NOW(),
    CONSTRAINT fk_css_course_section FOREIGN KEY (course_section_id)
        REFERENCES course_section(id),
    CONSTRAINT fk_css_room FOREIGN KEY (room_id)
        REFERENCES classrooms(id),
    CONSTRAINT chk_css_day_of_week CHECK (day_of_week >= 2 AND day_of_week <= 8),
    CONSTRAINT chk_css_start_period CHECK (start_period >= 1),
    CONSTRAINT chk_css_number_of_periods CHECK (number_of_periods >= 1),
    CONSTRAINT chk_css_time CHECK (start_time IS NULL OR end_time IS NULL OR start_time < end_time)
);

CREATE INDEX IF NOT EXISTS idx_css_section_day
    ON course_section_schedule(course_section_id, day_of_week);

CREATE INDEX IF NOT EXISTS idx_css_room_day
    ON course_section_schedule(room_id, day_of_week);

CREATE INDEX IF NOT EXISTS idx_css_cancel
    ON course_section_schedule(is_cancel);

-- Backfill: each existing course_section currently has one weekly schedule
INSERT INTO course_section_schedule (
    course_section_id,
    day_of_week,
    start_period,
    number_of_periods,
    start_time,
    end_time,
    room_id,
    is_cancel,
    created_at,
    updated_at
)
SELECT
    cs.id,
    cs.day_of_week,
    cs.start_period,
    cs.number_of_periods,
    cs.start_time,
    cs.end_time,
    cs.room_id,
    cs.is_cancel,
    cs.created_at,
    cs.updated_at
FROM course_section cs
WHERE NOT EXISTS (
    SELECT 1
    FROM course_section_schedule css
    WHERE css.course_section_id = cs.id
);

COMMIT;
