from enum import Enum


class ERROR_CODES:
    class CAMERA(str, Enum):
        CAMERA_NOT_FOUND = "CAMERA_NOT_FOUND"
        CAMERA_NAME_IS_EXISTED = "CAMERA_NAME_IS_EXISTED"
        IP_ADDRESS_IS_EXISTED = "IP_ADDRESS_IS_EXISTED"
        CLASSROOM_ALREADY_HAS_CAMERA = "CLASSROOM_ALREADY_HAS_CAMERA"

    class CLASSROOM(str, Enum):
        CLASSROOM_NOT_FOUND = "CLASSROOM_NOT_FOUND"
        CLASS_NAME_IS_EXISTED = "CLASS_NAME_IS_EXISTED"

    class COURSE(str, Enum):
        COURSE_NOT_FOUND = "COURSE_NOT_FOUND"
        COURSE_NAME_IS_EXISTED = "COURSE_NAME_IS_EXISTED"

    class COURSE_SECTION(str, Enum):
        COURSE_SECTION_NOT_FOUND = "COURSE_SECTION_NOT_FOUND"
        COURSE_SECTION_NAME_IS_EXISTED = "COURSE_SECTION_NAME_IS_EXISTED"
        LECTURER_NOT_FOUND = "LECTURER_NOT_FOUND"
        INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
        INVALID_TIME_RANGE = "INVALID_TIME_RANGE"
